name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: line-walker
  IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/line-walker:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        project_id: ${{secrets.GCP_PROJECT_ID}}
        workload_identity_provider: 'projects/642993486547/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'mitsuYashi@${{secrets.GCP_PROJECT_ID}}.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Login GCP
      run: gcloud --quiet auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet

    - name: Build a docker image
      run: docker build -t asia.gcr.io/$PROJECT_ID/line-walker:${{ github.sha }} ./app

    - name: Push the docker image to Container Registry
      run: docker push asia.gcr.io/$PROJECT_ID/line-walker:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
          gcloud run deploy $SERVICE_NAME \
            --image asia.gcr.io/$PROJECT_ID/line-walker:${{ github.sha }} \
            --project $PROJECT_ID \
            --region "asia-northeast1" \
            --platform=managed \
            --allow-unauthenticated \
            --quiet